import { state as s } from './state.js';
import * as ui from './ui.js';
import { connectWallet, getWalletState, disconnectWallet, observeWallet, readToken, deployToken, transferToken, verifyTransfer } from './wallet.js';
const { esc, icon, short, number, euros, price, exactQuantity }=ui;
const dialog=document.querySelector('#dialog');
let rendering=0;

async function api(path,options={}){
  const headers={...(options.body?{'Content-Type':'application/json'}:{}),...options.headers};
  if(s.session?.csrf_token&&options.method&&options.method!=='GET')headers['X-CSRF-Token']=s.session.csrf_token;
  let response;
  try{response=await fetch(path,{credentials:'same-origin',...options,headers});}catch{throw new Error('La console non risponde. Controlla che il server locale sia avviato.');}
  if(!response.ok){const data=await response.json().catch(()=>({}));let message=data.detail||`Richiesta non riuscita (${response.status})`;if(Array.isArray(message))message=message.map(x=>x.msg).join('; ');if(response.status===401&&path!=='/api/login'){s.session=null;ui.renderAuth(false);}throw new Error(typeof message==='string'?message:JSON.stringify(message));}
  return options.raw?response:response.status===204?null:response.json();
}
function toast(message,error=false){const node=document.createElement('div');node.className=`toast${error?' error':''}`;node.textContent=message;document.querySelector('#toast-region').append(node);setTimeout(()=>node.remove(),error?9000:4500);}
async function download(path,filename){const response=await api(path,{raw:true}),url=URL.createObjectURL(await response.blob()),anchor=document.createElement('a');anchor.href=url;anchor.download=filename;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function loadView(){if(!s.session?.authenticated)return;const version=++rendering,route=ui.currentRoute();ui.frame();const main=document.querySelector('#main');main.innerHTML='<div class="loading-view">Caricamento dei dati del progetto…</div>';try{const values=await Promise.all([api('/api/overview'),...(route==='overview'||route==='blockchain'?[api('/api/chain')]:[]),...(route==='overview'||route==='sales'?[api('/api/sales')]:[]),...(route==='whitepaper'?[api('/api/whitepaper')]:[])]);if(version!==rendering||!s.session?.authenticated)return;s.overview=values.shift();s.overview.prices.sort((a,b)=>a.id-b.id);if(route==='overview'||route==='blockchain')s.chain=values.shift();if(route==='overview'||route==='sales')s.sales=values.shift();if(route==='whitepaper')s.paper=values.shift();main.innerHTML=ui.renderPage();}catch(error){if(s.session?.authenticated)main.innerHTML=`<div class="notice"><p>${esc(error.message)}</p><button class="small section-gap" data-action="reload">Riprova</button></div>`;}}
function modal(title,content,description=''){dialog.innerHTML=`<div class="dialog-head"><div><h2 id="dialog-title">${title}</h2>${description?`<p>${description}</p>`:''}</div><button class="icon-button ghost" data-action="close-dialog" aria-label="Chiudi">${icon('close')}</button></div>${content}`;if(!dialog.open)dialog.showModal();}
function field(name,label,value='',options={}){const attributes=`${options.required===false?'':'required'} ${options.placeholder?`placeholder="${esc(options.placeholder)}"`:''}`;return `<div class="field ${options.full?'full':''}"><label for="input-${name}">${label}</label>${options.textarea?`<textarea name="${name}" id="input-${name}" ${attributes}>${esc(value)}</textarea>`:`<input name="${name}" id="input-${name}" type="${options.type||'text'}" value="${esc(value)}" ${attributes}>`}${options.help?`<small>${options.help}</small>`:''}</div>`;}
const formActions=label=>`<div class="dialog-actions"><button type="button" data-action="close-dialog">Annulla</button><button class="primary" type="submit">${label}</button></div>`;
function newSale(){modal('Nuova vendita',`<form id="sale-form"><div class="form-grid">${field('customer','Cliente','',{full:true,placeholder:'Nome o riferimento del cliente'})}${field('wallet_address','Wallet destinatario','',{full:true,placeholder:'0x…'})}${field('quantity','Quantità FIG','',{placeholder:'1000'})}${field('unit_price_eur','Prezzo per FIG · EUR',s.overview.stats.price_eur||'',{placeholder:'0.00001'})}<div class="field full"><label for="currency">Valuta del pagamento</label><select name="payment_currency" id="currency"><option>EUR</option><option>ETH</option><option>QNT</option></select><small>Il valore dell’ordine resta espresso in EUR al prezzo indicato.</small></div>${field('notes','Note','',{full:true,required:false,textarea:true})}</div>${formActions('Crea ordine')}</form>`,'L’ordine riserva token di distribuzione; non invia denaro o token.');}
function newTransaction(){modal('Transazione BlackChain',`<form id="transaction-form"><div class="form-grid"><div class="field"><label for="tx-sender">Mittente della demo</label><select name="sender" id="tx-sender"><option value="alice">Alice</option><option value="bob">Bob</option><option value="carol">Carol</option></select></div><div class="field"><label for="tx-kind">Operazione</label><select name="kind" id="tx-kind"><option value="transfer">Trasferimento</option><option value="stake">Stake</option><option value="unstake">Unstake</option><option value="ai_result">Attestazione IA</option></select></div><div class="field tx-amount"><label for="tx-amount">Unità simulate</label><input type="number" min="1" step="1" value="10" name="amount" id="tx-amount"></div><div class="field tx-recipient"><label for="tx-recipient">Destinatario</label><select name="recipient" id="tx-recipient"><option value="bob">Bob</option><option value="alice">Alice</option><option value="carol">Carol</option></select></div><div class="field full tx-text" hidden><label for="tx-text">Testo per il modello dimostrativo</label><textarea name="text" id="tx-text">Questo progetto è ottimo</textarea><small>Verranno registrati hash del testo e risultato firmato.</small></div></div>${formActions('Firma e metti in attesa')}</form>`,'Usa le chiavi del simulatore locale; queste operazioni non muovono FIG.');}
function addPrice(){modal('Registra un prezzo',`<form id="price-form"><div class="stack">${field('price_eur','Prezzo per FIG · EUR','',{placeholder:'0.00001'})}${field('source','Fonte della rilevazione','Inserimento manuale',{placeholder:'Rilevazione personale, URL, mercato…'})}</div>${formActions('Salva rilevazione')}</form>`,'Il grafico usa le tue rilevazioni con data e fonte; non è una quotazione automatica.');}
function parseFounders(value){if(!value.trim())return [{address:'',bps:3000}];return value.trim().split('\n').filter(line=>line.trim()).map(line=>{const [address,raw,...extra]=line.trim().split(';');if(extra.length||!raw||!/^\d{1,2}(?:[.,]\d{1,2})?$/.test(raw.trim()))throw new Error('Formato richiesto: indirizzo;percentuale, con massimo due decimali.');const [whole,fraction='']=raw.trim().replace(',','.').split('.');return {address:address.trim(),bps:Number(whole)*100+Number(fraction.padEnd(2,'0'))};});}

async function submittedError(error){if(error.txHash){modal('Transazione inviata · verifica richiesta',`<p>La transazione è stata inviata al wallet. Non ripetere l’invio prima di verificarne l’esito.</p><pre class="detail-code">${esc(error.txHash)}</pre><p>${esc(error.message)}</p><div class="dialog-actions"><button data-action="close-dialog">Chiudi</button></div>`);}else toast(error.message,true);}
async function onSubmit(event){const form=event.target;if(!(form instanceof HTMLFormElement))return;event.preventDefault();const data=Object.fromEntries(new FormData(form)),button=form.querySelector('button[type="submit"]');if(button)button.disabled=true;try{
  if(form.id==='auth-form'){const setup=form.dataset.setup==='true';if(setup&&data.password!==data.confirm)throw new Error('Le password non corrispondono.');s.session=await api(setup?'/api/setup':'/api/login',{method:'POST',body:JSON.stringify({password:data.password})});await loadView();return;}
  if(form.id==='sale-form'){await api('/api/sales',{method:'POST',body:JSON.stringify(data)});dialog.close();toast('Ordine creato e salvato.');}
  if(form.id==='price-form'){await api('/api/prices',{method:'POST',body:JSON.stringify(data)});dialog.close();toast('Prezzo e fonte salvati.');}
  if(form.id==='transaction-form'){const payload={sender:data.sender,kind:data.kind};if(data.kind==='ai_result')payload.text=data.text;else{payload.amount=Number(data.amount);if(!Number.isSafeInteger(payload.amount)||payload.amount<1)throw new Error('Inserisci un numero intero positivo.');}if(data.kind==='transfer')payload.recipient=data.recipient;await api('/api/chain/transactions',{method:'POST',body:JSON.stringify(payload)});dialog.close();toast('Transazione firmata, pronta per il prossimo blocco.');}
  if(form.id==='settings-form'){data.chain_id=Number(data.chain_id);data.founders=parseFounders(data.founders);if(!Number.isSafeInteger(data.chain_id)||data.chain_id<1)throw new Error('Chain ID non valido.');await api('/api/settings',{method:'PATCH',body:JSON.stringify(data)});s.liveToken=null;toast('Impostazioni salvate.');}
  if(form.id==='whitepaper-form'){await api('/api/whitepaper',{method:'PUT',body:JSON.stringify({fields:data})});toast('Nuova versione del white paper salvata.');}
  if(form.id==='paid-form'){await api(`/api/sales/${form.dataset.id}`,{method:'PATCH',body:JSON.stringify({status:'paid',payment_reference:data.payment_reference})});dialog.close();toast('Pagamento registrato.');}
  if(form.id==='generic-transfer-form'){const result=await transferToken(s.overview.settings,{recipient:data.recipient,quantity:data.quantity});dialog.close();toast(`Trasferimento confermato: ${short(result.txHash)}`);s.liveToken=await readToken(s.overview.settings.contract_address,s.overview.settings.chain_id);}
  if(form.id==='verify-sale-form'){const row=s.sales.find(row=>String(row.id)===form.dataset.id);await finishExistingTransfer(row,data.tx_hash);dialog.close();toast('Trasferimento verificato e ordine completato.');}
  await loadView();
}catch(error){if(form.id==='auth-form'){const target=document.querySelector('#auth-error');if(target){target.hidden=false;target.textContent=error.message;}}else await submittedError(error);}finally{if(button)button.disabled=false;}}

async function recordDelivery(row,txHash,config=s.overview.settings){await api(`/api/sales/${row.id}/delivery`,{method:'POST',body:JSON.stringify({tx_hash:txHash,chain_id:config.chain_id,contract_address:config.contract_address})});}
async function finishExistingTransfer(row,txHash){if(!s.wallet)s.wallet=await connectWallet();const config=row.delivery_contract?{...s.overview.settings,contract_address:row.delivery_contract,chain_id:row.delivery_chain_id}:s.overview.settings;const result=await verifyTransfer(config,txHash,{recipient:row.wallet_address,quantity:row.quantity});await api(`/api/sales/${row.id}/delivery`,{method:'POST',body:JSON.stringify({tx_hash:result.txHash,chain_id:result.chainId,contract_address:config.contract_address})});await api(`/api/sales/${row.id}`,{method:'PATCH',body:JSON.stringify({status:'completed',tx_hash:result.txHash})});}
async function action(name,target){
  if(name==='close-dialog'){dialog.close();return;}
  if(name==='reload'){await loadView();return;}
  if(name==='logout'){await api('/api/logout',{method:'POST'});s.session=null;s.wallet=null;s.liveToken=null;disconnectWallet();ui.renderAuth(false);return;}
  if(name==='wallet'){if(s.wallet){modal('Wallet collegato',`<dl class="description-list"><dt>Indirizzo</dt><dd class="mono">${esc(s.wallet.address)}</dd><dt>Chain ID</dt><dd>${s.wallet.chainId}</dd></dl><div class="dialog-actions"><button data-action="disconnect-wallet">Scollega dalla console</button><button data-action="close-dialog" class="primary">Chiudi</button></div>`);return;}s.wallet=await connectWallet();toast(`Wallet collegato sulla rete ${s.wallet.chainId}.`);refreshWalletUI();return;}
  if(name==='disconnect-wallet'){disconnectWallet();s.wallet=null;s.liveToken=null;dialog.close();refreshWalletUI();return;}
  if(name==='new-sale'){newSale();return;}
  if(name==='new-transaction'){newTransaction();return;}
  if(name==='add-price'){addPrice();return;}
  const downloads={backup:['/api/backup','figurae-backup.json'],'sales-csv':['/api/sales/export.csv','figurae-vendite.csv'],'prices-csv':['/api/prices/export.csv','figurae-prezzi.csv'],'contract-source':['/api/contract/source','Figurae.sol'],'export-chain':['/api/chain/export','blackchain-registro.json'],'whitepaper-md':['/api/whitepaper/export.md','figurae-whitepaper.md']};
  if(downloads[name]){await download(...downloads[name]);return;}
  if(name==='whitepaper-pdf'){window.print();return;}
  if(name==='forge'){await api('/api/chain/forge',{method:'POST',body:'{}'});toast('Blocco creato, verificato e salvato.');await loadView();return;}
  if(name==='block-details'){const b=s.chain.blocks.find(b=>String(b.height)===target.dataset.id);modal(`Blocco #${b.height}`,`<dl class="description-list"><dt>Proponente</dt><dd class="mono">${esc(b.proposer)}</dd><dt>Hash</dt><dd class="mono">${esc(b.hash)}</dd><dt>State root</dt><dd class="mono">${esc(b.state_root)}</dd></dl><h3 style="font-size:15px">Transazioni e firma</h3><pre class="detail-code">${esc(JSON.stringify(b,null,2))}</pre>`);return;}
  if(name==='import-chain'){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{try{const file=input.files[0];if(!file)return;if(file.size>10*1024*1024)throw new Error('Registro troppo grande (massimo 10 MiB).');const archive=JSON.parse(await file.text());modal('Importa registro',`<p>Il file contiene ${Array.isArray(archive.blocks)?archive.blocks.length:'?'} blocchi. Il registro locale verrà sostituito dopo la verifica di firme e stato.</p><div class="dialog-actions"><button data-action="close-dialog">Annulla</button><button id="confirm-import" class="primary">Verifica e importa</button></div>`);document.querySelector('#confirm-import').onclick=async event=>{event.target.disabled=true;try{await api('/api/chain/import',{method:'POST',body:JSON.stringify(archive)});dialog.close();toast('Registro verificato e importato.');await loadView();}catch(error){toast(error.message,true);event.target.disabled=false;}};}catch(error){toast(error.message,true);}};input.click();return;}
  if(name==='read-token'){if(!s.wallet)s.wallet=await connectWallet();if(!s.overview.settings.contract_address)throw new Error('Configura prima l’indirizzo del contratto Figurae.');s.liveToken=await readToken(s.overview.settings.contract_address,s.overview.settings.chain_id);toast('Supply e saldo letti dal contratto.');await loadView();return;}
  if(name==='deploy-token'){if(s.overview.settings.contract_address)throw new Error('È già configurato un contratto. Modifica le impostazioni solo per creare una nuova emissione separata.');if(!s.wallet)s.wallet=await connectWallet();const config=s.overview.settings;if(!config.founders.some(f=>f.address)||!config.distribution_wallet)throw new Error('Configura gli indirizzi dei proprietari e del wallet di distribuzione.');modal('Pubblicazione Figurae',`<p>Creerai un nuovo contratto su <strong>${esc(config.network_name)}</strong> (Chain ID ${config.chain_id}).</p><div class="confirm-details"><p>Supply: <strong>100.000.000.000 FIG</strong></p><p>Proprietari: 30.000.000.000 FIG</p><p>Distribuzione: 70.000.000.000 FIG</p><p class="mono">${esc(config.distribution_wallet)}</p></div><p class="help">Il wallet mostrerà il costo di rete e chiederà la tua firma. Per una prima prova usa Sepolia.</p><div class="dialog-actions"><button data-action="close-dialog">Annulla</button><button class="primary" id="confirm-deploy">Continua nel wallet</button></div>`);document.querySelector('#confirm-deploy').onclick=async event=>{event.target.disabled=true;try{const artifact=await api('/api/artifact'),result=await deployToken(config,artifact);try{await api('/api/settings',{method:'PATCH',body:JSON.stringify({contract_address:result.address})});}catch(error){modal('Contratto creato · salva l’indirizzo',`<p>Il deployment è confermato. Non ripeterlo. Inserisci questo indirizzo nelle impostazioni:</p><pre class="detail-code">${esc(result.address)}</pre><p class="mono">${esc(result.txHash)}</p><p>${esc(error.message)}</p>`);return;}dialog.close();toast(`Contratto creato: ${short(result.address)}`);s.liveToken=await readToken(result.address,config.chain_id);await loadView();}catch(error){await submittedError(error);event.target.disabled=false;}};return;}
  if(name==='fill-wallet'){if(!s.wallet)s.wallet=await connectWallet();document.querySelector('#founders').value=`${s.wallet.address};30`;toast('Wallet inserito come proprietario. Salva le impostazioni.');return;}
  if(name==='transfer-token'){if(!s.wallet)s.wallet=await connectWallet();modal('Trasferisci FIG',`<form id="generic-transfer-form"><div class="stack">${field('recipient','Destinatario','',{placeholder:'0x…'})}${field('quantity','Quantità FIG','',{placeholder:'1000'})}<p class="help">Rete ${esc(s.overview.settings.network_name)} · il wallet mostrerà quantità, destinatario e commissione prima della firma.</p></div>${formActions('Continua nel wallet')}</form>`);return;}
  if(name.startsWith('sale-')){const row=s.sales.find(r=>String(r.id)===target.dataset.id);if(!row)throw new Error('Ordine non trovato.');
    if(name==='sale-details'){modal(`Vendita · ${esc(row.customer)}`,`<dl class="description-list"><dt>Stato</dt><dd>${ui.badge(row.status)}</dd><dt>Destinatario</dt><dd class="mono">${esc(row.wallet_address)}</dd><dt>Quantità</dt><dd>${exactQuantity(row.quantity)} FIG</dd><dt>Prezzo</dt><dd>${price(row.unit_price_eur)}</dd><dt>Valore ordine</dt><dd>${price(row.total_eur)}</dd><dt>Pagamento</dt><dd>${esc(row.payment_currency)} · ${esc(row.payment_reference||'Non registrato')}</dd><dt>Hash consegna</dt><dd class="mono">${esc(row.tx_hash||'Non registrato')}</dd><dt>Note</dt><dd>${esc(row.notes||'—')}</dd></dl><div class="dialog-actions">${row.status==='paid'?`<button data-action="sale-verify" data-id="${row.id}">Verifica trasferimento esistente</button>`:''}${['pending','paid'].includes(row.status)&&!row.tx_hash?`<button class="danger" data-action="sale-cancel" data-id="${row.id}">Annulla registrazione</button>`:''}<button data-action="close-dialog">Chiudi</button></div>`);return;}
    if(name==='sale-paid'){modal('Registra pagamento ricevuto',`<form id="paid-form" data-id="${row.id}"><div class="confirm-details"><p>${esc(row.customer)} · ${exactQuantity(row.quantity)} FIG</p><p>Valore ordine: ${price(row.total_eur)} · valuta ${esc(row.payment_currency)}</p></div>${field('payment_reference','Riferimento del pagamento ricevuto','',{help:'Ricevuta, riferimento bancario o hash della transazione ricevuta.'})}${formActions('Conferma registrazione')}</form>`,'La console registra la tua conferma; non incassa il pagamento automaticamente.');return;}
    if(name==='sale-verify'||(name==='sale-transfer'&&row.tx_hash)){modal('Verifica un trasferimento esistente',`<form id="verify-sale-form" data-id="${row.id}">${field('tx_hash','Hash trasferimento',row.tx_hash||'',{placeholder:'0x…'})}<p class="help">Verrà verificata la conferma sulla rete, il contratto, il mittente, il destinatario e la quantità FIG.</p>${formActions('Verifica e completa ordine')}</form>`);return;}
    if(name==='sale-cancel'){modal('Annulla registrazione',`<p>L’ordine di ${esc(row.customer)} verrà annullato nel registro. Eventuali pagamenti già ricevuti non vengono restituiti da questa operazione.</p><div class="dialog-actions"><button data-action="close-dialog">Torna all’ordine</button><button class="danger" id="confirm-cancel">Annulla registrazione</button></div>`);document.querySelector('#confirm-cancel').onclick=async()=>{try{await api(`/api/sales/${row.id}`,{method:'PATCH',body:JSON.stringify({status:'cancelled'})});dialog.close();toast('Registrazione annullata.');await loadView();}catch(error){toast(error.message,true);}};return;}
    if(name==='sale-transfer'){const deliveryConfig={...s.overview.settings};if(!s.wallet)s.wallet=await connectWallet();if(!s.overview.settings.distribution_wallet||s.wallet.address.toLowerCase()!==s.overview.settings.distribution_wallet.toLowerCase())throw new Error('Per consegnare un ordine collega il wallet di distribuzione configurato.');modal('Consegna token al cliente',`<div class="confirm-details"><p>Cliente: <strong>${esc(row.customer)}</strong></p><p>Quantità: <strong>${exactQuantity(row.quantity)} FIG</strong></p><p>Rete: ${esc(s.overview.settings.network_name)} (${s.overview.settings.chain_id})</p><p class="mono">${esc(row.wallet_address)}</p></div><p class="help">L’hash viene salvato appena la transazione è inviata. L’ordine si completa dopo la conferma della rete.</p><div class="dialog-actions"><button data-action="close-dialog">Annulla</button><button class="primary" id="confirm-delivery">Continua nel wallet</button></div>`);document.querySelector('#confirm-delivery').onclick=async event=>{event.target.disabled=true;try{const result=await transferToken(deliveryConfig,{recipient:row.wallet_address,quantity:row.quantity,onSubmitted:async submitted=>{row.tx_hash=submitted.txHash;await recordDelivery(row,submitted.txHash,deliveryConfig);}});try{await api(`/api/sales/${row.id}`,{method:'PATCH',body:JSON.stringify({status:'completed',tx_hash:result.txHash})});}catch(error){modal('Trasferimento effettuato · registrazione da completare',`<p>I token sono stati inviati. Non ripetere il trasferimento. Verifica questo hash dai dettagli dell’ordine:</p><pre class="detail-code">${esc(result.txHash)}</pre><p>${esc(error.message)}</p>`);return;}dialog.close();toast('Trasferimento confermato e ordine aggiornato.');await loadView();}catch(error){if(error.txHash)row.tx_hash=error.txHash;await submittedError(error);event.target.disabled=false;}};return;}
  }
}

document.addEventListener('submit',onSubmit);
document.addEventListener('click',async event=>{const target=event.target.closest('[data-action]');if(!target)return;event.preventDefault();const wasDisabled=target.disabled;target.disabled=true;try{await action(target.dataset.action,target);}catch(error){await submittedError(error);}finally{target.disabled=wasDisabled;}});
document.addEventListener('change',event=>{if(event.target.id==='tx-kind'){const kind=event.target.value;document.querySelector('.tx-amount').hidden=kind==='ai_result';document.querySelector('.tx-recipient').hidden=kind!=='transfer';document.querySelector('.tx-text').hidden=kind!=='ai_result';}if(event.target.id==='sales-filter'){s.salesFilter=event.target.value;refreshSales();}});
document.addEventListener('input',event=>{if(event.target.id==='sales-search'){s.salesSearch=event.target.value;refreshSales();}});
function refreshSales(){document.querySelector('#sales-table').innerHTML=ui.salesTable(ui.filteredSales());}
window.addEventListener('hashchange',loadView);
function refreshWalletUI(){const button=document.querySelector('.topbar [data-action=wallet]');if(button){button.className=s.wallet?'ghost':'primary';button.innerHTML=icon('wallet')+(s.wallet?esc(short(s.wallet.address,4)):'Collega wallet');}if(ui.currentRoute()==='token'&&s.overview&&document.querySelector('#main'))document.querySelector('#main').innerHTML=ui.renderPage();}
observeWallet(wallet=>{s.wallet=wallet;s.liveToken=null;if(s.session?.authenticated)refreshWalletUI();});
function registerWebTools(){const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController(),tools=[{name:'read_figurae_overview',title:'Leggi stato Figurae',description:'Legge tokenomics, statistiche gestionali e stato del registro dalla console autenticata.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},async execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Nessun parametro richiesto.');if(!s.session?.authenticated)throw new Error('Accedi prima alla console.');return await api('/api/overview');}},{name:'open_figurae_view',title:'Apri una vista Figurae',description:'Apre una sezione senza effettuare operazioni sul wallet.',inputSchema:{type:'object',properties:{view:{type:'string',enum:Object.keys(ui.routes)}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){if(!input||Object.keys(input).length!==1||!Object.hasOwn(ui.routes,input.view))throw new Error('Vista non valida.');if(!s.session?.authenticated)throw new Error('Accedi prima alla console.');location.hash=input.view;await loadView();return {view:input.view,title:ui.routes[input.view][0]};}}];for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
async function start(){try{s.session=await api('/api/session');s.wallet=getWalletState();if(s.session.authenticated)await loadView();else ui.renderAuth(s.session.setup_required);registerWebTools();}catch(error){document.querySelector('#app').innerHTML=`<div class="auth-page"><section class="auth-card">${ui.brand}<h1>Console non disponibile</h1><p>${esc(error.message)}</p><button id="retry-start" class="primary">Riprova</button></section></div>`;document.querySelector('#retry-start').onclick=()=>location.reload();}}
start();
